console.log('Loading Chef Boiardee...')
require('./Bots/CB/index')
console.log('Loading Instructions Follower...')
require('./Bots/FMOI/index')
console.log('Loading Garlic Bread Bot...')
require('./Bots/GBB/index')
console.log('Loading Thesaurusify Bot...')
require('./Bots/TB/index')
console.log('Loading Text-To-Emoji Bot...')
require('./Bots/TTEB/index')
console.log(`----------------\nAll Bots Loaded\nStarted @ ${Date()}\n----------------`) 